# Generated by Django 3.1.2 on 2020-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.CharField(max_length=10)),
                ('a2', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='cht',
            new_name='start_time',
        ),
    ]
