# Generated by Django 3.1.2 on 2020-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20201026_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='room_no',
        ),
        migrations.AddField(
            model_name='bookings',
            name='accessory',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='discount',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='end_time',
            field=models.CharField(default='24 hours', max_length=40),
        ),
        migrations.AddField(
            model_name='bookings',
            name='insurance',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='No name', max_length=20),
        ),
    ]
