# Generated by Django 3.1.2 on 2020-10-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_auto_20201026_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='cycle_accessories',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('costperitem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cycle_category',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('costperday', models.IntegerField()),
                ('latefeesperhour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('discount_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('expiry_date', models.DateField()),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('insurance_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('costperday', models.IntegerField()),
                ('coverage_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='end_time',
            field=models.TimeField(default='24 hours', max_length=40),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='start_time',
            field=models.TimeField(max_length=40),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='tot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.userinfo'),
        ),
        migrations.CreateModel(
            name='cycle',
            fields=[
                ('cycle_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('model_year', models.CharField(max_length=5)),
                ('model', models.CharField(max_length=40)),
                ('availability', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.cycle_category')),
            ],
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateField()),
                ('bill_status', models.CharField(max_length=40)),
                ('discount_amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('tax_amount', models.IntegerField()),
                ('total_late_fee', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.bookings')),
            ],
        ),
        migrations.AlterField(
            model_name='bookings',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.cycle_accessories'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.discount'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.insurance'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='lastpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lastpt', to='basicapp.location'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='startpt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startpt', to='basicapp.location'),
        ),
    ]
