# Generated by Django 3.1.2 on 2020-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20201026_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
