# Generated by Django 3.1.2 on 2020-10-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20201027_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cycle_id',
            field=models.ForeignKey(default='Unavailable', on_delete=django.db.models.deletion.CASCADE, to='basicapp.cycle'),
        ),
    ]
