# Generated by Django 3.1.2 on 2020-10-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_auto_20201027_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
