# Generated by Django 3.1.2 on 2020-10-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_auto_20201027_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='user',
            field=models.CharField(default='user', max_length=40),
        ),
    ]
