# Generated by Django 3.1.2 on 2020-10-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_cycle_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
