# Generated by Django 3.1.2 on 2020-10-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0013_auto_20201028_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(max_length=10),
        ),
    ]
