# Generated by Django 3.1.2 on 2020-10-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0014_auto_20201028_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='quantity',
        ),
    ]
